//
//  UIConstants.h
//  Hexatone
//
//  Created by Glenn Barnett on 3/15/09.
//  Copyright 2009 Impresario Digital. All rights reserved.
//

#define UI_SCREEN_WIDTH 480
#define UI_SCREEN_HEIGHT 320

#define UI_DRAGSTRIP_WIDTH 1201
#define UI_DRAGSTRIP_HEIGHT 48

#define UI_MINIMAP_HEIGHT 44 //was:44

#define UI_KEYS_WIDTH 1281
#define UI_KEYS_HEIGHT 205
#define UI_KEYS_OFFSET 40

#define UI_MAINCONTROLS_HEIGHT 115
#define UI_MAINCONTROLS_FONT @"HelveticaNeue"
#define UI_MAINCONTROLS_FONTSIZE 16.0

#define UI_KEYS_OCTAVELABEL_FONT_NAME @"Georgia"
#define UI_KEYS_OCTAVELABEL_FONT_SIZE 48
#define UI_KEYS_OCTAVELABEL_OPACITY 0.5

#define UI_KEYS_NOTELABELBUFFERLEFT 2.0
#define UI_KEYS_NOTELABELPADDING 0

#define UI_KEYS_NOTELABELBIG_FONT_NAME @"HelveticaNeue-Bold"
#define UI_KEYS_NOTELABELBIG_FONT_SIZE 32
#define UI_KEYS_NOTELABELBIG_OPACITY 0.6
#define UI_KEYS_NOTELABELBIG_WIDTH 80
#define UI_KEYS_NOTELABELBIG_HEIGHT 40

#define UI_KEYS_NOTELABELUPPER_OFFSET 10
#define UI_KEYS_NOTELABELLOWER_OFFSET 141

#define UI_KEYS_NOTELABELSMALL_XOFFSET 0
#define UI_KEYS_NOTELABELSMALL_YOFFSETTOP 33
#define UI_KEYS_NOTELABELSMALL_YOFFSETBOT 33
#define UI_KEYS_NOTELABELSMALL_FONT_NAME @"HelveticaNeue-Bold"
#define UI_KEYS_NOTELABELSMALL_FONT_SIZE 12
#define UI_KEYS_NOTELABELSMALL_OPACITY 0.6
#define UI_KEYS_NOTELABELSMALL_WIDTH 80
#define UI_KEYS_NOTELABELSMALL_HEIGHT 15


#define UI_KEYS_TIPLABELSMALL_FONT_NAME @"Thonburi"
#define UI_KEYS_TIPLABELBIG_FONT_NAME @"Thonburi"
#define UI_KEYS_TIPLABELSMALL_FONT_SIZE 18
#define UI_KEYS_TIPLABELBIG_FONT_SIZE 18

// GSB: left/right orientation
//#define UI_KEYS_NOTELABELBUFFERLEFT 0.0
//#define UI_KEYS_NOTELABELPADDING 0 //15
//
//#define UI_KEYS_NOTELABELBIG_FONT_NAME @"Helvetica-Bold"
//#define UI_KEYS_NOTELABELBIG_FONT_SIZE 48
//#define UI_KEYS_NOTELABELBIG_OPACITY 0.5
//#define UI_KEYS_NOTELABELBIG_WIDTH 44
//#define UI_KEYS_NOTELABELBIG_HEIGHT 40
//
//#define UI_KEYS_NOTELABELLOWER_OFFSET 145
//#define UI_KEYS_NOTELABELUPPER_OFFSET 10
//
//#define UI_KEYS_NOTELABELSMALL_XOFFSET 44
//#define UI_KEYS_NOTELABELSMALL_YOFFSETTOP 3
//#define UI_KEYS_NOTELABELSMALL_YOFFSETBOT 3
//#define UI_KEYS_NOTELABELSMALL_FONT_NAME @"Helvetica-Bold"
//#define UI_KEYS_NOTELABELSMALL_FONT_SIZE 12
//#define UI_KEYS_NOTELABELSMALL_OPACITY 0.55
//#define UI_KEYS_NOTELABELSMALL_WIDTH 50
//#define UI_KEYS_NOTELABELSMALL_HEIGHT 32

#define UI_PRESETLABEL_FONT_SIZE 24

#define UI_MAINBUTTON_CLEARANCE 36
#define UI_SOUNDADJUST_WIDTH 473
#define UI_SOUNDADJUST_HEIGHT 81
#define UI_SOUNDADJUST_OFFSETX 0 // 7
#define UI_SOUNDADJUST_OFFSETY 2 //35

#define UI_KEYS_INITIAL_OFFSET -281
#define UI_KEYS_PIXELS_PER_OCTAVE 240
#define UI_KEYS_PIXELS_PER_NOTE 80

#define UI_PATCHPICKERVC_WIDTH 144 
#define UI_PATCHPICKERVC_HEIGHT 287 
#define UI_PATCHPICKERVC_XOFFSET 69
#define UI_PATCHPICKERVC_YOFFSET 33 // down 
#define UI_PATCHPICKERVC_HEIGHT_SHORT 87

#define UI_SCALEPICKERVC_WIDTH 144 
#define UI_SCALEPICKERVC_HEIGHT 287 
#define UI_SCALEPICKERVC_XOFFSET 308
#define UI_SCALEPICKERVC_YOFFSET 33 // down 
#define UI_SCALEPICKERVC_HEIGHT_SHORT 87 

#define UI_LOOPPICKERVC_WIDTH 274
#define UI_LOOPPICKERVC_HEIGHT 284
#define UI_LOOPPICKERVC_XOFFSET 118
#define UI_LOOPPICKERVC_YOFFSET 36 // down 
#define UI_LOOPPICKERVC_HEIGHT_SHORT 84

#define UI_RECPICKERVC_WIDTH 274
#define UI_RECPICKERVC_HEIGHT 284
#define UI_RECPICKERVC_XOFFSET 68
#define UI_RECPICKERVC_YOFFSET 33 // down 
#define UI_RECPICKERVC_HEIGHT_SHORT 84


#define UIColorFromRGB(rgbValue) [UIColor \
									colorWithRed:((float)((rgbValue & 0xFF0000) >> 16))/255.0 \
									green:((float)((rgbValue & 0xFF00) >> 8))/255.0 \
									blue:((float)(rgbValue & 0xFF))/255.0 alpha:1.0]

